// Description: Family tree data for the family tree app.
export const familyTree = {
  0: {
    id: 0,
    firstname: "",
    lastname: "",
    birth: "",
    death: "",
    spouse: [],
    parents: [],
    gender: "",
    deleted: false,
    deceased: false,
  },
  1: {
    id: 1,
    firstname: "John",
    lastname: "Doe",
    birth: "1852-04-24",
    death: "1920-03-12",
    spouse: [5],
    parents: [21, 22],
    gender: "M",
    deleted: false,
    deceased: true,
  },
  2: {
    id: 2,
    firstname: "Anne",
    lastname: "Doe",
    birth: "1875-06-15",
    death: "1950-08-20",
    spouse: [6],
    parents: [1, 5],
    gender: "F",
    maidenName: "Doe",
    deleted: false,
    deceased: true,
  },
  3: {
    id: 3,
    firstname: "Jane",
    lastname: "Doe",
    birth: "1878-09-10",
    death: "1960-11-25",
    spouse: [7],
    parents: [1, 5],
    gender: "F",
    maidenName: "Doe",
    deleted: false,
    deceased: true,
  },
  4: {
    id: 4,
    firstname: "Mary",
    lastname: "Doe",
    birth: "1880-12-05",
    death: "1965-07-30",
    spouse: [8],
    parents: [1, 5],
    gender: "F",
    maidenName: "Doe",
    deleted: false,
    deceased: true,
  },
  5: {
    id: 5,
    firstname: "Janine",
    lastname: "Doe",
    birth: "1855-03-22",
    death: "1930-01-15",
    spouse: [1],
    parents: [23, 24],
    gender: "F",
    maidenName: "Smith",
    deleted: false,
    deceased: true,
  },
  6: {
    id: 6,
    firstname: "Mark",
    lastname: "Smith",
    birth: "1870-02-14",
    death: "1945-09-10",
    spouse: [2],
    parents: [],
    gender: "M",
    deleted: false,
    deceased: true,
  },
  7: {
    id: 7,
    firstname: "Paul",
    lastname: "Brown",
    birth: "1873-05-18",
    death: "1955-12-22",
    spouse: [3],
    parents: [],
    gender: "M",
    deleted: false,
    deceased: true,
  },
  8: {
    id: 8,
    firstname: "Luke",
    lastname: "White",
    birth: "1872-11-11",
    death: "1957-04-05",
    spouse: [4],
    parents: [],
    gender: "M",
    deleted: false,
    deceased: true,
  },
  9: {
    id: 9,
    firstname: "Emily",
    lastname: "Green",
    birth: "1900-07-07",
    death: "1980-02-28",
    spouse: [10],
    parents: [],
    gender: "F",
    maidenName: "Green",
    deleted: false,
    deceased: true,
  },
  10: {
    id: 10,
    firstname: "Michael",
    lastname: "Black",
    birth: "1898-01-01",
    death: "1975-06-15",
    spouse: [9],
    parents: [],
    gender: "M",
    deleted: false,
    deceased: true,
  },
  11: {
    id: 11,
    firstname: "David",
    lastname: "Doe",
    birth: "1925-05-20",
    death: "",
    spouse: [17],
    parents: [2, 6],
    gender: "M",
    deleted: false,
    deceased: true,
  },
  12: {
    id: 12,
    firstname: "James",
    lastname: "Doe",
    birth: "1950-03-10",
    death: "",
    spouse: [18],
    parents: [11, 17],
    gender: "M",
    deleted: false,
    deceased: false,
  },
  13: {
    id: 13,
    firstname: "Emma",
    lastname: "White",
    birth: "1953-07-25",
    death: "",
    spouse: [19],
    parents: [11, 17],
    gender: "F",
    maidenName: "Doe",
    deleted: false,
    deceased: true,
  },
  14: {
    id: 14,
    firstname: "Sophia",
    lastname: "Doe",
    birth: "1975-09-15",
    death: "",
    spouse: [],
    parents: [12, 18],
    gender: "F",
    maidenName: "Doe",
    deleted: false,
    deceased: false,
  },
  15: {
    id: 15,
    firstname: "Daniel",
    lastname: "Doe",
    birth: "1978-11-30",
    death: "",
    spouse: [],
    parents: [12, 18],
    gender: "M",
    deleted: false,
    deceased: false,
  },
  16: {
    id: 16,
    firstname: "Olivia",
    lastname: "White",
    birth: "1980-04-22",
    death: "",
    spouse: [],
    parents: [13, 19],
    gender: "F",
    deleted: false,
    deceased: false,
  },
  17: {
    id: 17,
    firstname: "Sarah",
    lastname: "Doe",
    birth: "1927-08-18",
    death: "",
    spouse: [11],
    parents: [],
    gender: "F",
    maidenName: "Johnson",
    deleted: false,
    deceased: true,
  },
  18: {
    id: 18,
    firstname: "Laura",
    lastname: "Doe",
    birth: "1952-02-14",
    death: "",
    spouse: [12],
    parents: [],
    gender: "F",
    maidenName: "Wilson",
    deleted: false,
    deceased: false,
  },
  19: {
    id: 19,
    firstname: "Robert",
    lastname: "White",
    birth: "1950-06-30",
    death: "",
    spouse: [13],
    parents: [],
    gender: "M",
    deleted: false,
    deceased: false,
  },
  20: {
    id: 20,
    firstname: "Mike",
    lastname: "Doe",
    birth: "2000-01-01",
    death: "",
    spouse: [],
    parents: [15],
    gender: "M",
    deleted: false,
    deceased: false,
  },
  21: {
    id: 21,
    firstname: "William",
    lastname: "Doe",
    birth: "1820-01-01",
    death: "1880-01-01",
    spouse: [22],
    parents: [],
    gender: "M",
    deleted: false,
    deceased: true,
  },
  22: {
    id: 22,
    firstname: "Elizabeth",
    lastname: "Doe",
    birth: "1825-01-01",
    death: "1890-01-01",
    spouse: [21],
    parents: [],
    gender: "F",
    maidenName: "Brown",
    deleted: false,
    deceased: true,
  },
  23: {
    id: 23,
    firstname: "Tom",
    lastname: "Smith",
    birth: "1822-01-01",
    death: "1885-01-01",
    spouse: [24],
    parents: [],
    gender: "M",
    deleted: false,
    deceased: true,
  },
  24: {
    id: 24,
    firstname: "Marie",
    lastname: "Smith",
    birth: "1827-01-01",
    death: "1895-01-01",
    spouse: [23],
    parents: [],
    gender: "F",
    maidenName: "Johnson",
    deleted: false,
    deceased: true,
  },
  25: {
    id: 25,
    firstname: "George",
    lastname: "Doe",
    birth: "1985-05-15",
    death: "",
    spouse: [26],
    parents: [14, 29],
    gender: "M",
    deleted: false,
    deceased: false,
  },
  26: {
    id: 26,
    firstname: "Alice",
    lastname: "Doe",
    birth: "1987-07-20",
    death: "",
    spouse: [25],
    parents: [],
    gender: "F",
    maidenName: "Brown",
    deleted: false,
    deceased: false,
  },
  27: {
    id: 27,
    firstname: "Henry",
    lastname: "Doe",
    birth: "2010-03-10",
    death: "",
    spouse: [],
    parents: [25, 26],
    gender: "M",
    deleted: false,
    deceased: false,
  },
  28: {
    id: 28,
    firstname: "Grace",
    lastname: "Doe",
    birth: "2012-08-25",
    death: "",
    spouse: [],
    parents: [25, 26],
    gender: "F",
    deleted: false,
    deceased: false,
  },
  29: {
    id: 29,
    firstname: "Thomas",
    lastname: "Wilson",
    birth: "1970-04-10",
    death: "",
    spouse: [14],
    parents: [],
    gender: "M",
    deleted: false,
    deceased: false,
  },
  30: {
    id: 30,
    firstname: "Ella",
    lastname: "Doe",
    birth: "2022-05-10",
    death: "",
    spouse: [],
    parents: [28],
    gender: "F",
    deleted: false,
    deceased: false,
  },
  31: {
    id: 31,
    firstname: "Jack",
    lastname: "Doe",
    birth: "2023-11-15",
    death: "",
    spouse: [],
    parents: [28],
    gender: "M",
    deleted: false,
    deceased: false,
  },
  32: {
    id: 32,
    firstname: "Liam",
    lastname: "Doe",
    birth: "2024-07-20",
    death: "",
    spouse: [],
    parents: [28],
    gender: "M",
    deleted: false,
    deceased: false,
  },
};
